server:
  port: 8769

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-garage
          uri: lb://garage-service
          predicates:
            - Path=/garage/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
